name: grovers_env
channels:
  - defaults
dependencies:
  - python=3.10.13
  - jupyter
  - matplotlib
  - pip
  - pip:
    - qiskit
    - qiskit-aer
    - qiskit-terra
    - pylatexenc
    - seaborn
    - numpy